---
- hosts: ansible_test
  tasks:
    - name: dnf upgrafe
      ansible.builtin.dnf:
       name: "*"
       state: latest
      become: true

    - name: Create test directory
      file:
        path: "~/test_dir"
        state: directory

    - name: Install cronie
      ansible.builtin.dnf:
       name: cronie
       state: latest
      become: true
 
    #テスト 
    - name: Cron test
      ansible.builtin.cron:
        name: test
        user: root
	hour: "12"
        job: 'echo "test has executed!" >> /var/log/test.log'
        cron_file: cron-test
      become: true

　  #第一金曜日にupdateする
    - name: Cron first Friday execute
      ansible.builtin.cron:
       name: "dnf Update"
       minute: "0"
       hour: "0"
       day: "1-7"
       weekday: "5"
       user: "root"
       job: "dnf -y update > /var/log/dnf-update.log 2>&1"
      become: true

